select * from customer;


-- total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue from customer group by gender;


-- used discount but still paid more than average amount
select customer_id, purchase_amount
from customer
where discount_applied="Yes" and purchase_amount >=(select avg(purchase_amount) from customer);


-- top5 products with highest avg review rating
select item_purchased, round(avg(review_rating),2) as average_product_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- compare avg purchase amount bw std and xpress shipping
select shipping_type, round(avg(purchase_amount) ,2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type ;


-- subcription avg spend and total revenue vs non subscribed avg spend and total revenue
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as revenue, round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status;


-- top 5 items with highest discount rates
select item_purchased, round(100 * sum(case when discount_applied="Yes" then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Segment customers into New, Returning, and Loyal based on their total no. of previous purchases and show the count of each segment
with customer_type as (
select customer_id , previous_purchases,
case 
when previous_purchases=1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal"
end as customer_segment
from customer
)
select customer_segment , count(*) as "no. of customer"
from customer_type
group by customer_segment;


-- top 3 most purchases products within each category
with item_counts as (
select item_purchased, category, count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3; 


-- revenue contribution of each age group
select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc;